package com.freeroom.persistence.proxy;

import com.freeroom.persistence.beans.Book;
import org.junit.BeforeClass;
import org.junit.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class HadesTest
{
    private static Hades hades;

    @BeforeClass
    public static void setUp() throws SQLException
    {
        prepareDB();
        hades = new Hades(getDbProperties());
    }

    @Test
    public void should_get_simple_record()
    {
        final Book book = hades.create(Book.class, 1);

        assertThat(book.getIsbn(), is(123L));
        assertThat(book.getName(), is("JBoss Seam"));
    }

    @Test
    public void should_know_simple_record_has_been_changed()
    {
        final Book book = hades.create(Book.class, 1);
        book.setName("Learning Node");

        assertThat(hades.isDirty(book), is(true));
    }

    private static Properties getDbProperties()
    {
        final Properties properties = new Properties();
        properties.setProperty("url", "jdbc:hsqldb:mem:mydb");
        properties.setProperty("username", "sa");
        properties.setProperty("password", "");
        return properties;
    }

    private static void prepareDB() throws SQLException
    {
        try(final Connection connection = DriverManager.getConnection("jdbc:hsqldb:mem:mydb", "sa", "")) {
            final Statement statement = connection.createStatement();
            try {
                statement.executeUpdate("DROP TABLE PUBLIC.BOOK");
            } catch (Exception ignored) {}
            statement.executeUpdate(
                    "CREATE MEMORY TABLE PUBLIC.BOOK("+
                            "ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"+
                            "ISBN INTEGER,"+
                            "NAME VARCHAR(50))");
            statement.executeUpdate("INSERT INTO PUBLIC.BOOK (ID, ISBN, NAME) VALUES (1, 123, 'JBoss Seam')");
            statement.close();
        }
    }
}
