package com.freeroom.persistence;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

public class DBFixture
{
    public static Properties getDbProperties()
    {
        final Properties properties = new Properties();
        properties.setProperty("url", "jdbc:hsqldb:mem:mydb");
        properties.setProperty("username", "sa");
        properties.setProperty("password", "");
        properties.setProperty("blockSize", "2");
        return properties;
    }

    public static void prepareDB() throws SQLException
    {
        try(final Connection connection = DriverManager.getConnection("jdbc:hsqldb:mem:mydb", "sa", "")) {
            final Statement statement = connection.createStatement();
            try {
                statement.executeUpdate("DROP TABLE PUBLIC.BOOK");
                statement.executeUpdate("DROP TABLE PUBLIC.ORDER");
                statement.executeUpdate("DROP TABLE PUBLIC.PUBLISHER");
                statement.executeUpdate("DROP TABLE PUBLIC.READER");
            } catch (Exception ignored) {}

            statement.executeUpdate(
                    "CREATE MEMORY TABLE PUBLIC.BOOK("+
                            "BOOKID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "+
                            "PUBLISHER_PUBLISHERID INTEGER, ISBN INTEGER, NAME VARCHAR(50), PRICE DECIMAL(8,2), "+
                            "PUBLISHDATE DECIMAL(12,0), TAGS VARCHAR(255))");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.BOOK (PUBLISHER_PUBLISHERID, ISBN, NAME, PRICE, PUBLISHDATE, TAGS) "+
                    "VALUES (1, 123, 'JBoss Seam', 18.39, 1234567890, '101,102')");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.BOOK (PUBLISHER_PUBLISHERID, ISBN, NAME, PRICE, PUBLISHDATE, TAGS) "+
                    "VALUES (1, 128, 'Bootstrap', 18.39, 1234567896, '101')");

            statement.executeUpdate(
                    "CREATE MEMORY TABLE PUBLIC.ORDER("+
                            "ORDERID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "+
                            "BOOK_BOOKID INTEGER, AMOUNT INTEGER, MEMO VARCHAR(255))");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.ORDER (BOOK_BOOKID, AMOUNT, MEMO) "+
                    "VALUES (1, 8, 'Deliver at work time')");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.ORDER (BOOK_BOOKID, AMOUNT, MEMO) "+
                    "VALUES (1, 1, 'Deliver at night')");

            statement.executeUpdate(
                    "CREATE MEMORY TABLE PUBLIC.PUBLISHER("+
                            "PUBLISHERID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "+
                            "NAME VARCHAR(50), PROFILE VARCHAR(255))");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.PUBLISHER (NAME, PROFILE) "+
                    "VALUES ('O Reilly', 'A Publisher')");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.PUBLISHER (NAME, PROFILE) "+
                    "VALUES ('Wrox', 'Programmer To Programmer')");

            statement.executeUpdate(
                    "CREATE MEMORY TABLE PUBLIC.READER("+
                            "READERID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "+
                            "NAME VARCHAR(50), BOOK_BOOKID INTEGER)");
            statement.executeUpdate(
                    "INSERT INTO PUBLIC.READER (NAME, BOOK_BOOKID) "+
                    "VALUES ('lly', 1)");

            statement.close();
        }
    }
}
